# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: 
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}

          # Options
          user: P4ND4P0W3R
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, introduction, lines, languages, isocalendar
          config_timezone: Europe/Paris

          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: yes
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
